### ISSUE TITLE
Failed at the ripple-lib@0.17.7 compile script.

### ISSUE THREAD

**Issue by estevaocm** [LedgerHQ/ripple-recovery-tool#3]
Please help. npm version is 5.6.0

```
estevao@ubuntuvm:~/ripple-recovery-tool/ripple-lib$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> sauce-connect-launcher@0.14.0 postinstall /home/estevao/ripple-recovery-tool/ripple-lib/node_modules/sauce-connect-launcher
> node scripts/install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> ripple-lib@0.17.7 prepublish /home/estevao/ripple-recovery-tool/ripple-lib
> npm run clean && npm run compile


> ripple-lib@0.17.7 clean /home/estevao/ripple-recovery-tool/ripple-lib
> rm -rf dist/npm && rm -rf build/flow


> ripple-lib@0.17.7 compile /home/estevao/ripple-recovery-tool/ripple-lib
> babel -D --optional runtime -d dist/npm/ src/

module.js:540
    throw err;
    ^

Error: Cannot find module 'lodash/kebabCase'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/estevao/ripple-recovery-tool/ripple-lib/node_modules/babel-cli/lib/babel/index.js:12:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ripple-lib@0.17.7 compile: `babel -D --optional runtime -d dist/npm/ src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ripple-lib@0.17.7 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/estevao/.npm/_logs/2018-01-05T00_39_39_801Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ripple-lib@0.17.7 prepublish: `npm run clean && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ripple-lib@0.17.7 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/estevao/.npm/_logs/2018-01-05T00_39_39_904Z-debug.log
```

**Comment by estevaocm** [comment]
```
estevao@ubuntuvm:~/ripple-recovery-tool$ npm install

> secp256k1@3.2.5 install /home/estevao/ripple-recovery-tool/node_modules/secp256k1
> prebuild-install || node-gyp rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/secp256k1-v3.2.5-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/estevao/.npm/_prebuilds/https-github.com-cryptocoinjs-secp256k1-node-releases-download-v3.2.5-secp256k1-v3.2.5-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/cryptocoinjs/secp256k1-node/releases/download/v3.2.5/secp256k1-v3.2.5-node-v57-linux-x64.tar.gz
prebuild-install http 404 https://github.com/cryptocoinjs/secp256k1-node/releases/download/v3.2.5/secp256k1-v3.2.5-node-v57-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.9.4 runtime=node arch=x64 platform=linux)
make: Entering directory '/home/estevao/ripple-recovery-tool/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  COPY Release/secp256k1.node
make: Leaving directory '/home/estevao/ripple-recovery-tool/node_modules/secp256k1/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ripple-recovery-tool@0.0.1 No repository field.
npm WARN ripple-recovery-tool@0.0.1 No license field.

added 109 packages in 16.834s
```

**Comment by estevaocm** [comment]
```
estevao@ubuntuvm:~/ripple-recovery-tool$ node CLI-recovery-tool.js 
module.js:540
    throw err;
    ^

Error: Cannot find module './ripple-lib/dist/npm/index.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/estevao/ripple-recovery-tool/CLI-recovery-tool.js:1:83)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

```

**Comment by estevaocm** [comment]
Upgraded to npm 5.5.1 and got the same error.

**Comment by estevaocm** [comment]
I had success with
`npm install ripple-lib`

However, still same runtime error:
```
estevao@ubuntuvm:~/ripple-recovery-tool$ node CLI-recovery-tool.js 
module.js:557
    throw err;
    ^

Error: Cannot find module './ripple-lib/dist/npm/index.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/estevao/ripple-recovery-tool/CLI-recovery-tool.js:1:83)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

```

**Comment by estevaocm** [comment]
Also:
```
estevao@ubuntuvm:~/ripple-recovery-tool/ripple-lib$ npm install
path.js:1175
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1175:25)
    at Function.Module._resolveLookupPaths (module.js:431:17)
    at Function.Module._resolveFilename (module.js:549:20)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)

```

**Comment by estevaocm** [comment]
I was only able to run the recovery-tool by cloning and installing https://github.com/ripple/ripple-lib

**Comment by estevaocm** [comment]
While I solved my problem, it might be interesting to update the ripple-lib directory whenever possible,
